app/models.py
from . import db


class Feature(db.Model):
    __tablename__ = 'Feature'

    id = db.Column(db.String(40), primary_key=True, index=True, unique=True)
    feature = db.Column(db.Text)
    label = db.Column(db.Integer)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, IntegerField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileRequired, FileAllowed


class UploadDataForm(FlaskForm):
    file = FileField('请选择.dat文件', validators=[FileRequired(), FileAllowed(['dat'])])
    label = IntegerField("数据标签", validators=[DataRequired()])
    submit = SubmitField('上传')


class TestForm(FlaskForm):
    file = FileField('请选择.dat文件', validators=[FileRequired(), FileAllowed(['dat'])])
    submit = SubmitField('测试')

app/__init__.py
from flask import Flask, render_template
from config import config
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap

bootstrap = Bootstrap()
db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)

    # 在工厂函数 create_app() 中 将蓝本注册到应用上
    from app.main import main as main_blueprint
    app.register_blueprint(main_blueprint, url_prefix='/')

    return app

app/main/__init__.py
from flask import Blueprint


main = Blueprint('main', __name__)


from . import views

app/main/views.py
from flask import render_template, flash, redirect, url_for
from .forms import UploadDataForm, TestForm
from . import main
import uuid
import random
import matlab.engine
from ..models import Feature
from .. import db
import json
import time


def generate_uuid():
    return str(uuid.uuid5(uuid.NAMESPACE_DNS, str(uuid.uuid1()) + str(random.random())))


@main.route('/', methods=['GET', 'POST'])
def home():
    return redirect(url_for('.database'))


@main.route('/database', methods=['GET', 'POST'])
def database():
    form = UploadDataForm()
    if form.validate_on_submit():
        file = form.file.data
        label = form.label.data
        filename = generate_uuid() + ".dat"
        file.save("app/code/test-data/" + filename)
        engine = matlab.engine.start_matlab()
        engine.cd("app/code/", nargout=1)
        feature = engine.FS("test-data/" + filename)
        new_feature = Feature(id=generate_uuid(), feature=str(feature), label=label)
        db.session.add(new_feature)
        db.session.commit()
        flash("上传成功！")
        return redirect(url_for('.database'))
    features = Feature.query.order_by(Feature.label.asc()).all()
    return render_template("database.html", form=form, features=features)


@main.route('/delete-feature/<id>', methods=['GET', 'POST'])
def delete_feature(id):
    feature = Feature.query.filter_by(id=id).first_or_404()
    db.session.delete(feature)
    db.session.commit()
    return redirect(url_for('.database'))


@main.route('/test-database', methods=['GET', 'POST'])
def test_database():
    form = TestForm()
    feature = ""
    judge_res = ""
    test_duration = ""
    if form.validate_on_submit():
        if Feature.query.count() == 0:
            flash("请先录入指纹数据！")
            return redirect(url_for(".database"))
        # 1、存储上传的.dat文件
        file = form.file.data
        filename = generate_uuid() + ".dat"
        dat_file_path = "test-data/" + filename
        file.save("app/code/" + dat_file_path)

        # 2、启动Matlab引擎
        engine = matlab.engine.start_matlab()
        engine.cd("app/code/", nargout=1)

        # 3、获得指纹库，并生成指纹库的.mat文件
        features = Feature.query.all()
        featureMatrix = "["
        for feature in features:
            f = eval(feature.feature)[0]
            for item in f:
                featureMatrix += str(item) + " "
            featureMatrix += str(feature.label)
            featureMatrix += ";"
        featureMatrix = featureMatrix[0: -1] + "]"
        filename = generate_uuid() + ".mat"
        mat_file_path = "mats/" + filename
        matlabCode = "finger_database = " + str(featureMatrix) + "; save(\"" + mat_file_path + "\", \"finger_database\");"
        tic = time.time()
        engine.eval(matlabCode, nargout=0)
        toc = time.time()
        test_duration = str(toc - tic).split('.')[0] + "." + str(toc - tic).split('.')[1][0: 2] + "s"
        # 4、拿到特征
        feature = engine.FS(dat_file_path)

        # 5、判断设备合法性
        judge_res = engine.Test(dat_file_path, mat_file_path, nargout=1)

        # 6、停止引擎
        engine.quit()
    return render_template("test_database.html", form=form, feature=feature, judge_res=judge_res, test_duration=test_duration)


@main.route('/test-model', methods=['GET', 'POST'])
def test_model():
    form = UploadDataForm()
    classification = -1
    if form.validate_on_submit():
        file = form.file.data
        filename = generate_uuid() + ".dat"
        file.save("app/code/test-data/" + filename)
        engine = matlab.engine.start_matlab()
        engine.cd("app/code/", nargout=1)
        classification = int(engine.FS_C("test-data/" + filename))
        engine.quit()
        flash("上传成功！")
    return render_template("test_model.html", form=form, classification=classification)


@main.route('/test', methods=['GET', 'POST'])
def test():
    features = Feature.query.all()
    featureMatrix = "["
    for feature in features:
        f = eval(feature.feature)[0]
        for item in f:
            featureMatrix += str(item) + " "
        featureMatrix += str(feature.label)
        featureMatrix += ";"
    featureMatrix = featureMatrix[0: -1] + "]"
    engine = matlab.engine.start_matlab()
    filename = generate_uuid() + ".mat"
    engine.cd("app/code/", nargout=1)
    matlabCode = "finger_database = " + str(featureMatrix) + "; save(\"mats/" + filename + "\", \"finger_database\");"
    engine.eval(matlabCode, nargout=0)
    engine.quit()
    return json.dumps(featureMatrix)

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
    IPv6环境下基于WiFi信道状态的非法设备识别平台设计
{% endblock %}

{% block navbar %}

    {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
    {% endfor %}


        <div class="row" style="margin: 0; padding: 0;">
            <div class="container-fluid">
                <img src="{{ url_for("static", filename='top.jpeg') }}" alt="" style="width: 100%; margin: 0; padding: 0;">
            </div>
        </div>
    <div class="navbar navbar-inverse" role="navigation">
        <div class="row" style="width: 100%; margin: 0; padding: 0;">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="/" class="navbar-brand">GERNET</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/">主页</a></li>
                        <li><a href={{ url_for("main.database") }}>数据库</a></li>
                        <li><a href={{ url_for("main.test_database") }}>数据测试</a></li>
{#                        <li><a href={{ url_for("main.test_model") }}>模型测试</a></li>#}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="page-header" style="margin-top: 20px; margin-bottom: 10px; padding: 0px;">
            <h4>IPv6环境下基于WiFi信道状态的非法设备识别平台设计</h4>
            <p>{% block subtitle %}{% endblock %}</p>
        </div>
        <div class="page-body">
            {% block page_content %}
            {% endblock %}
        </div>
    </div>
    <img src="{{ url_for("static", filename='logo.png') }}" alt="" style="position: fixed; right: 30px; bottom: 20px; width: 80px;">
{% endblock %}

app/templates/database.html
{% extends "base.html" %}

{% block subtitle %}
    指纹库信息管理
{% endblock %}

{% block page_content %}


    <div style="padding-top: 0px; padding-bottom: 15px;">
        <form method="post" action="{{ url_for("main.database") }}" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="row">
            <div class="container">
                <div class="col-lg-3" style="padding: 0;">
                    {{ form.file(class="form-control", accept=".dat") }}
                </div>
                <div class="col-lg-3" style="padding: 0; padding-left: 5px;">
                    {{ form.label(class="form-control", placeholder="输入样本标签") }}
                </div>
                <div class="col-lg-3" style="padding: 0; padding-left: 5px;">
                    {{ form.submit(class="btn btn-primary") }}
                </div>
            </div>
            </div>
        </form>
    </div>
    <table class="table table-bordered table-hover table-responsive table-striped table-condensed"
        style="table-layout: fixed; word-break: break-all;"
    >
    <thead>
        <tr style="text-align: center;">
            <td style="width: 5%;">序号</td>
            <td style="width: 80%;">特征</td>
            <td style="width: 5%;">标签</td>
            <td style="width: 5%;">操作</td>
        </tr>
    </thead>
    <tbody>

    {% for feature in features %}
        <tr style="text-align: center;">
            <td style="display:table-cell; vertical-align:middle;">{{ loop.index }}</td>
            <td>{{ feature.feature }}</td>
            <td style="display:table-cell; vertical-align:middle;">{{ feature.label }}</td>
            <td style="display:table-cell; vertical-align:middle">
                <a href="{{ url_for("main.delete_feature", id=feature.id) }}"><span class="label label-danger" style="cursor: pointer;">删除</span></a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}

app/templates/test_database.html
{% extends "base.html" %}

{% block subtitle %}
    基于指纹库测试
{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="container">
            <div style="padding-top: 0px; padding-bottom: 15px;">
                <form method="post" action="{{ url_for("main.test_database") }}" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                        <div class="col-lg-6" style="padding: 0;">
                            {{ form.file(class="form-control", accept=".dat") }}
                        </div>
                        <div class="col-lg-6" style="padding: 0; padding-left: 5px;">
                            {{ form.submit(class="btn btn-primary") }}
                            <a href="{{ url_for("main.test_database") }}"><span class="btn btn-default">清空结果</span></a>
                        </div>
                </form>
            </div>
        </div>
    </div>
    {% if feature != "" and judge_res != "" and test_duration != ""  %}
        <div class="row">
            <div class="container">
                <div class="col-lg-6" style="padding: 0;">
                    <br>
                    <p><b>数据特征</b></p>
                    <p style="word-break:break-all; width:600px;">{{ feature }}</p>
                    <p><b>判断结果</b></p>
                    <p>{{ judge_res }}</p>
                    <p><b>测试时长</b></p>
                    <p>{{ test_duration }}</p>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

app/templates/test_model.html
{% extends "base.html" %}

{% block subtitle %}
    基于机器学习模型测试
{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="col-lg-6">
            {{ wtf.quick_form(form) }}
        </div>
        <div class="col-lg-6">
            {% if classification != -1 %}
                <h4>分类结果：{{ classification }}</h4>
            {% endif %}
        </div>
    </div>
{% endblock %}